#!/bin/bash
set -o errexit

mkdir -p ebin
mkdir -p bin
erlc -o ebin src/indents.erl
erlc -o ebin src/cerlish.erl
erl -noinput -eval 'neotoma:file("grammar/erlish.peg").' -run init stop
#sed -i.bk 's/p(Inp, StartIndex, Name, ParseFun, TransformFun) ->/& io:format("~s | ~p | ~p~n", [Name, StartIndex, case Inp of [I|_]->[I];_->"eof" end]),/' grammar/erlish.erl
erlc -o ebin grammar/erlish.erl
#rm grammar/erlish.erl
rm -f erlish.erl.bk
rm -f grammar/erlish.erl.bk
erl -noinput -eval '
	zip:create(".cerlish.ez",
		["cerlish.beam", "indents.beam", "erlish.beam"],
		[{cwd,"ebin"},{compress, all}, {uncompress, [".beam", ".app"]}]).
	' -run init stop
echo '#!/usr/bin/env escript' > bin/cerlish
echo '%%! -smp enable +h 4096' >> bin/cerlish
cat .cerlish.ez >> bin/cerlish
chmod u+x bin/cerlish
rm .cerlish.ez
