#!/usr/bin/env escript
%%! -smp auto -pa /home/jwecker/gtd/projects/efene/ebin

main(_) ->
  S = socket_server:new(main_one, 3212),
  S:start(),
  S:cast("wow"),
  S:call("hmmm"),
  receive Any -> ok
  end.
  
